baseURL = "https://www.example.com/"
languageCode = "en-us"
title = "Raineys Property Management"
themesDir = "../.."
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-removebg-preview.png"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo-removebg-preview.png"
    desktop_height = "40px"
    desktop_width = "217px"
    alt = "Raineys Property Management"

  [params.homepage_meta_tags]
    meta_description = "A website to describe the work of Raineys Propertymangement and showcase past jobs in the housing renovation industry."
    meta_og_title = "Raineys Property Management"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "A website to describe the work of Raineys Propertymangement and showcase past jobs in the housing renovation industry."

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Portfolio"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Testimonials"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
